package autocode

type ServiceGroup struct {
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.
	AutoCodeExampleService
	UserInfoService
	StudentInfoService
	TeacherInfoService
	CompetitionInfoService
	CompetitionScheService
	CompanyInfoService
	TeamInfoService
	TeamMemberService
	EntryFormService
	EntryMemberService
	ProjectInfoService
	SwiperService
	ArticleService
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}
