package autocode

type ApiGroup struct {
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.
	AutoCodeExampleApi
	UserInfoApi
	CompetitionInfoApi
	CompetitionScheApi
	CompanyInfoApi
	TeamInfoApi
	TeamMemberApi
	EntryFormApi
	EntryMemberApi
	ProjectInfoApi
	SwiperApi
	ArticleApi
	StudentInfoApi
	TeacherInfoApi
	AchievementApi
	StudentRecruitApi
	TeacherRecruitApi
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}
