package autocode

type RouterGroup struct {
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.
	AutoCodeExampleRouter
	UserInfoRouter
	CompetitionInfoRouter
	CompetitionScheRouter
	CompanyInfoRouter
	TeamInfoRouter
	TeamMemberRouter
	EntryFormRouter
	EntryMemberRouter
	ProjectInfoRouter
	SwiperRouter
	ArticleRouter
	NoAuthRouter
	StudentInfoRouter
	TeacherInfoRouter
	AchievementRouter
	StudentRecruitRouter
	TeacherRecruitRouter
	ProduceComsumeInfomationRouter
	EntryTeacherRouter
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}
